Changed some wording
filc/website pull request #20
Opened 2022-12-08 21:12 UTC by xoudoesthings

2022-12-08 21:59 UTC, xoudoesthings commented on pages/index.tsx
> +            description="A kezdőlapodon könnyen leolvashatod a jelenlegi órád hátralévő időtartamát, helyét, és a következő órádat is."
made it clearer

2022-12-15 12:49 UTC, 55nknown requested changes
the customize animation has a constant background, needs to be removed (also there are some artifacts)

2022-12-15 15:10 UTC, xoudoesthings commented
Done

2022-12-25 15:58 UTC, 55nknown approved these changes

2022-12-25 15:59 UTC, merged